site_name: GitHub matters
repo_url: https://github.com/cambridge-ceu/GitHub-matters
edit_uri: ""
nav:
    - "   ": README.md
    - Contributors: contributors.md
    - Notes: Notes.md
    - "Web building": Flask.md
theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - Bash
        - HTML
        - Java
        - JavaScript
        - Perl
        - Python
        - R
        - rust
        - yaml

markdown_extensions:
  - footnotes
