openapi: 3.0.0
info:
  title: My REST API
  version: 1.0.0
paths:
  /api/hello:
    get:
      summary: Get a greeting message
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: {"message": "Hello, World!"}
