name: Swagger Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate HTML documentation via OpenAPI Generator
        uses: diegoara96/openapi-generator-action@v1
        with:
          spec-file: 'docs/openapi.yml'
          generator: 'html2'
          output-dir: 'swagger-html'

      - name: Upload generated docs as artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: swagger-html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.upload.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
